### PR TITLE
Build with circleci and bump drakecore

### PR DESCRIPTION
**Pull request by carolynvs**
* This builds with circleci for a bit until we are able to use brigade2 with drake.
* Bumps drakecore to pick up environment array->map change.

### CODE REVIEW

**Comment by krancour** [comment]
CI has been hung because of shenanigans in our cluster. Some certs got rotated and some stuff broke. I'll give it some love in the next few days to make sure things are running smoothly again. Give me a nudge if I forget.

**Comment by krancour** [comment]
It looks like unit tests are failing because the modified unit test job uses mage and mage wants a writable FS, but doesn't have one. Then the pipeline fails fast and, I think, status reporting for things that _did_ run is even being preempted.

So there are really two issues here and this PR isn't causing them so much as it's exposing them:

1. If status reporting was pre-empted, that's a brigdrake issue and isn't worth fixing because as we continue to adapt brigdrake for Brigade v2 compatibility, this isn't the worker's responsibility anyway. In fact, the relevant bits might even be gone from `master` already.

2. As for the unwritable file system...

    The spec says that jobs cannot modify source unless they explicitly declare that they do. Those that do are ineligible for inclusion in a pipeline. That may all seem a bit inconvenient, so I'm happy to revisit that part of the spec, but there were also, what I think, were defensible reasons for that decision...

    Recall that we want as similar an experience as possible across the developer's machine (using devdrake) and remote pipeline-executor (e.g. CI environments). In the remote case, jobs that need source snap it down from source control because that's actually _faster_ than grabbing it just once up front and putting it on a shared volume. _NFS is slow_. This means, remotely, every job is guaranteed a _pristine_ copy of the source code that is unaltered by jobs that have preceded it in the pipeline. _Locally_, source comes directly from your pwd instead of source control. But to match what goes on remotely, there needs to be the _same_ expectation locally that jobs don't modify source. So this expectation is enforced (both locally and remotely) by mounting source to a RO file system.

    As I mentioned, jobs can explicitly declare that they modify source, in which case, source gets mounted to a RW file system. This is convenient for jobs that you want to run locally and you fully _intend_ for them to have side effects. This would make sense, for instance, for a job that runs `go mod vendor` or something. But such jobs are ineligible to participate in pipelines because it would undermine the expectation that every job in a pipeline gets its own pristine, unmodified copy of the source regardless of _where_ the pipeline is running.

    A possible workaround is to copy the source to someplace else on the FS and cd to that location before running anything that would modify source. There might also be some mage options that can be explored.

    Of course, we can also revisit the problematic bits of the spec.

**Comment by carolynvs** [comment]
I don't think that there is a way to have mage run and not generate a file (without modifying mage). It generates `mage_output_file.go` in the repository as a temporary file. I can look into if we can patch mage to use /tmp or something but until then I'll apply your suggested tweak.

**Comment by krancour** [comment]
Not sure what's going on.... I will look shortly.

**Comment by krancour** [comment]
Ok... here's what's going on. Recall that we're using Brigade v1.x + my old prototype brigdrake to orchestrate CI at the moment. As things currently stand, that older version of brigdrake chokes on your `Drakefile.yaml`, which appears to have been adapted to conform to more recent spec changes you made:

```
2021/04/29 16:58:32 Starting BrigDrake worker -- version unstable -- commit 1eba3fb -- supports DrakeSpec v0.6.0
2021/04/29 16:58:33 loading configuration from "/vcs/Drakefile.yaml"
2021/04/29 16:58:33 error reading /vcs/Drakefile.yaml: error unmarshalling config file /vcs/Drakefile.yaml: Configuration is invalid: 
- jobs.build-darwin-amd64.primaryContainer.environment: Invalid type. Expected: array, given: object
- jobs.build-darwin-amd64.primaryContainer: Must validate all the schemas (allOf)
- jobs.build-windows-amd64.primaryContainer.environment: Invalid type. Expected: array, given: object
- jobs.build-windows-amd64.primaryContainer: Must validate all the schemas (allOf)
- jobs.build-linux-amd64.primaryContainer.environment: Invalid type. Expected: array, given: object
- jobs.build-linux-amd64.primaryContainer: Must validate all the schemas (allOf)
```

Perhaps the Drakefile needs to follow the older version of the spec for now?

**Pull request merged**
